sudo: false
language: node_js
node_js: 8.12.0
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run build
after_success:
  - npm run semantic-release